const { By, until } = require('selenium-webdriver')
const config = require('../../../config.json')

module.exports = {
    createExample: (driver) => createExample(driver)
}

async function createExample(driver) {
    console.log(config.space3 + "enter: tests->application->interface->createExample.js")
    await driver.navigate().refresh()
    console.log(config.space3 + "page refreshed")
    await driver.sleep(2000) // need to avoid the mistake about react error
    console.log(config.space3 + "slept 2 sec")
    await driver.wait(until.elementLocated(By.linkText("Examples")), config.waitTime)
    console.log(config.space3 + "link text \"Examples\" in tabs menu located")
    await driver.findElement(By.linkText("Examples")).click()
    console.log(config.space3 + "link text \"Examples\" in tabs menu clicked")
    await driver.wait(until.elementLocated(By.css(".TypedTable__bottomButton")), config.waitTime)
    console.log(config.space3 + "field \"+ Add example\" located")
    await driver.findElement(By.css(".TypedTable__bottomButton")).click()
    console.log(config.space3 + "field \"+ Add example\" clicked")
    await driver.wait(until.elementLocated(By.css(".ModalWindow__root__open")), config.waitTime)
    console.log(config.space3 + "modal window located")
    await driver.findElement(By.css(".EditorDialog__block:nth-child(1) .TextInput")).sendKeys("E1")
    console.log(config.space3 + "field \"Name\" filled with \"E1\"")
    await driver.findElement(By.css(".EditorDialog__block:nth-child(2) .TextArea")).sendKeys("ED")
    console.log(config.space3 + "field \"Description\" filled with \"ED\"")
    await driver.findElement(By.css(".EditorDialog__block:nth-child(3)")).click()
    console.log(config.space3 + "field \"Operation\" clicked")
    await driver.findElement(By.css(".EditorDialog__block:nth-child(3) .KascodeSelect__option:nth-child(1)")).click()
    console.log(config.space3 + "option \"O1\" in field \"Operation\" clicked")
    await driver.findElement(By.css(".EditorDialog__block:nth-child(4) .TextArea")).sendKeys("ET")
    console.log(config.space3 + "field \"Type\" filled with \"ET\"")
    await driver.findElement(By.css(".EditorDialog__block:nth-child(5)")).click()
    console.log(config.space3 + "field \"Response\" clicked")
    await driver.findElement(By.css(".EditorDialog__block:nth-child(5) .KascodeSelect__option:nth-child(1)")).click()
    console.log(config.space3 + "option \"R1\" in field \"Response\" clicked")
    await driver.findElement(By.css(".EditorDialog__block:nth-child(5) .TextArea")).sendKeys("ET")
    console.log(config.space3 + "field \"Type\" filled with \"ET\"")
    await driver.findElement(By.css(".btn_big.EditorDialog__button:nth-child(2)")).click()
    console.log(config.space3 + "field \"Create\" clicked")
    await driver.wait(until.stalenessOf(driver.findElement(By.css(".ModalWindow__root__open"))), config.waitTime)
    console.log(config.space3 + "modal window stale")
}